In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2 = np.array([[1,2,3],
                 [2.5,8,9]])
arr2

array([[1. , 2. , 3. ],
       [2.5, 8. , 9. ]])

In [4]:
arr1.dtype , arr2.dtype

(dtype('int64'), dtype('float64'))

In [5]:
arr1.shape , arr2.shape

((5,), (2, 3))

In [6]:
arr1.ndim ,arr2.ndim

(1, 2)

In [7]:
type(arr1) , type(arr2)
## ndarry is type of all array no matter what's datatype of array integer , float.

(numpy.ndarray, numpy.ndarray)

**Creat a DataFrame from array numpy**

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(arr2)
df
### This is important when you have a data not numercil i mean images so you convert these to numpy array and use pandas and matplotlib and machine learning model.

0    1    2
0  1.0  2.0  3.0
1  2.5  8.0  9.0

In [10]:
ones = np.ones((2,4),dtype = int)
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [11]:
zeros = np.zeros((2,3),dtype = float)
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [13]:
random_array = np.random.randint(0,10,size = (4,4))
random_array

array([[1, 1, 3, 1],
       [1, 1, 8, 1],
       [3, 7, 4, 5],
       [3, 6, 9, 4]])

In [14]:
random_array.dtype

dtype('int64')

In [15]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.2691943 , 0.4941011 , 0.87372318],
       [0.46318098, 0.02640927, 0.81403929],
       [0.04872102, 0.56748965, 0.78911074],
       [0.01408716, 0.11533022, 0.77339212],
       [0.33520724, 0.78450658, 0.19582691]])

In [16]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.43197894, 0.83042106, 0.48562035],
       [0.16622693, 0.0474907 , 0.19705371],
       [0.27371532, 0.64492341, 0.18837774],
       [0.34431603, 0.84674337, 0.26028141],
       [0.14863434, 0.61676629, 0.19127664]])

In [17]:
# pesudo_random numbers
np.random.seed(seed = 0)
random_array4 = np.random.randint(10,size = (2,2))
random_array4

array([[5, 0],
       [3, 3]])

In [18]:
np.unique(random_array4)

array([0, 3, 5])

In [19]:
# arr2
arr2[0][1] = 100

In [20]:
arr2

array([[  1. , 100. ,   3. ],
       [  2.5,   8. ,   9. ]])

** Matrix Operations**

In [21]:
matrix1 = np.array([[1, 3],
                   [5, 7]])
matrix2 = np.array([[2, 4],
                   [6, 8]])

In [22]:
matrix1 * matrix2

array([[ 2, 12],
       [30, 56]])

In [23]:
matrix2 * matrix1

array([[ 2, 12],
       [30, 56]])

In [24]:
2 * matrix1

array([[ 2,  6],
       [10, 14]])

In [25]:
matrix1 / matrix2

array([[0.5       , 0.75      ],
       [0.83333333, 0.875     ]])

# Use Python's methods (sum()) on Python datatypes and use Numpy's methods on Numpy arrays(np.sum()).


In [26]:
random_array3

array([[0.43197894, 0.83042106, 0.48562035],
       [0.16622693, 0.0474907 , 0.19705371],
       [0.27371532, 0.64492341, 0.18837774],
       [0.34431603, 0.84674337, 0.26028141],
       [0.14863434, 0.61676629, 0.19127664]])

In [27]:

%timeit sum(random_array3)
%timeit np.sum(random_array3)

12 µs ± 5.13 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
The slowest run took 5.05 times longer than the fastest. This could mean that an intermediate result is being cached.
9.88 µs ± 4.99 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [28]:
arr2

array([[  1. , 100. ,   3. ],
       [  2.5,   8. ,   9. ]])

In [29]:
np.max(arr2)

100.0

In [30]:
np.std(arr2)

35.63520808912943

In [31]:
np.var(arr2)

1269.8680555555557

In [32]:
np.median(arr2)

5.5

In [33]:
arr2.transpose()

array([[  1. ,   2.5],
       [100. ,   8. ],
       [  3. ,   9. ]])

**Dot Product**

In [34]:
np.random.seed(0)
mat1 = np.random.randint(10,size = (5,3))
mat2 = np.random.randint(10,size = (5,3))

In [35]:
mat2.transpose()

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [36]:
mat1.dot(mat2.transpose())

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

# **SORTING ARRAYS IN NUMPY**

In [37]:
random_array

array([[1, 1, 3, 1],
       [1, 1, 8, 1],
       [3, 7, 4, 5],
       [3, 6, 9, 4]])

In [38]:
np.sort(random_array)

array([[1, 1, 1, 3],
       [1, 1, 1, 8],
       [3, 4, 5, 7],
       [3, 4, 6, 9]])

In [39]:
np.argsort(random_array)

array([[0, 1, 3, 2],
       [0, 1, 3, 2],
       [0, 2, 3, 1],
       [0, 3, 1, 2]])

In [40]:
np.argmax(random_array)

14

In [41]:
np.argmin(random_array)

0

In [42]:
np.argsort(random_array, axis =0)

array([[0, 0, 0, 0],
       [1, 1, 2, 1],
       [2, 3, 1, 3],
       [3, 2, 3, 2]])

In [43]:
random_array

array([[1, 1, 3, 1],
       [1, 1, 8, 1],
       [3, 7, 4, 5],
       [3, 6, 9, 4]])

In [44]:
np.sort(random_array,axis = 0)

array([[1, 1, 3, 1],
       [1, 1, 4, 1],
       [3, 6, 8, 4],
       [3, 7, 9, 5]])

In [46]:
m = np.array([[1,2,3],
             [-6,0,2],
             [7,8,0]])
m

array([[ 1,  2,  3],
       [-6,  0,  2],
       [ 7,  8,  0]])

In [47]:
np.sort(m, axis = 0)

array([[-6,  0,  0],
       [ 1,  2,  2],
       [ 7,  8,  3]])

In [59]:
# <img src="numpy-images/panda.png"/>
from google.colab import files
# drive.mount('/content/drive')
from IPython.display import Image
# Image('numpy-images/panda.png')

In [60]:
uploded = files.upload()

Saving panda.png to panda.png


In [61]:
Image('panda.png',
      width= 1200)

Output hidden; open in https://colab.research.google.com to view.

In [62]:
from matplotlib.image import imread
panda = imread('panda.png')

In [64]:
panda.shape , panda.size , panda.ndim

((2330, 3500, 3), 24465000, 3)